services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/var/www
    networks:
      - app-network
    ports:
      - "9000:9000"  # PHP-FPMのポート
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    ports:
      - "8080:8080"  # Vueの開発サーバーのポート

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html
    ports:
      - "8000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
